sudo: required 
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - g++
  
# Build steps
script:
  - pwd
  - sudo apt-get install libxorg-gtest-dev
  - sudo apt-get install libcppunit-dev
  - sudo apt install libgtest-dev cmake
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd ~
  - cd build/capslockqq/TestRepoEclipse 
  - cd GTest/Debug
  - make clean
  - make
  - cd ../Sample-Test1
  - make clean
  - make
  - ls
  - ./Source.out
  
  
notifications:
  email: false
